"""Mobike analytics dashboard, backed by CSV files generated by the analyser."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from flask import Flask, jsonify, render_template


APP_DIR = Path(__file__).resolve().parent
PROJECT_DIR = APP_DIR.parent
DATA_DIR = PROJECT_DIR / "data"
SAMPLE_SIZE = 8_000

app = Flask(__name__)


def existing_csv(name: str) -> Path:
    path = DATA_DIR / name
    if not path.is_file():
        raise FileNotFoundError(f"Missing data file: {path}")
    return path


def numeric_histogram(values: pd.Series, bins: int, unit: str) -> dict[str, list[float] | str]:
    """Compact a continuous metric for a browser chart, ignoring invalid extremes."""
    values = pd.to_numeric(values, errors="coerce").dropna()
    values = values[values.ge(0)]
    if values.empty:
        return {"labels": [], "values": [], "unit": unit}
    upper = float(values.quantile(0.99))
    # Keep a meaningful domain for tightly clustered data.
    upper = max(upper, float(values.max()) if values.nunique() == 1 else 0.0)
    clipped = values.clip(upper=upper)
    counts, edges = np.histogram(clipped, bins=bins, range=(0, upper or 1))
    labels = [round(float(edge), 2) for edge in edges[:-1]]
    return {"labels": labels, "values": counts.tolist(), "unit": unit}


def dashboard_payload() -> dict:
    enriched = pd.read_csv(existing_csv("mobike_enriched.csv"), usecols=lambda col: col in {
        "ttl_min", "distance", "hourId", "hourType"
    })
    locations = pd.read_csv(existing_csv("dbscan_locations.csv"))
    cluster_counts = pd.read_csv(existing_csv("dbscan_cluster_counts.csv"))
    centers_path = DATA_DIR / "kmeans_centers.csv"
    centers = pd.read_csv(centers_path) if centers_path.is_file() else pd.DataFrame()

    hourly = (
        enriched.groupby("hourId").size().reindex(range(1, 25), fill_value=0)
    )
    valid_duration = pd.to_numeric(enriched["ttl_min"], errors="coerce")
    valid_distance = pd.to_numeric(enriched["distance"], errors="coerce")
    rush_share = (enriched["hourType"] == "rush hours").mean() * 100
    noise_count = int((locations["dbscan_label"] == -1).sum())

    # Preserve all cluster centres but sample individual points for a responsive map.
    display_points = locations.sample(min(len(locations), SAMPLE_SIZE), random_state=42)
    cluster_table = cluster_counts[cluster_counts["cluster"] != -1].nlargest(12, "count")
    return {
        "metrics": {
            "rides": int(len(enriched)),
            "averageDuration": round(float(valid_duration.mean()), 1),
            "averageDistance": round(float(valid_distance.mean()), 2),
            "rushShare": round(float(rush_share), 1),
            "noiseCount": noise_count,
        },
        "hourly": {"labels": [f"{hour:02d}:00" for hour in hourly.index], "values": hourly.tolist()},
        "duration": numeric_histogram(valid_duration, bins=24, unit="分钟"),
        "distance": numeric_histogram(valid_distance, bins=24, unit="公里"),
        "points": display_points[["longitude", "latitude", "dbscan_label"]].round(6).values.tolist(),
        "centers": centers[["longitude", "latitude", "size"]].round(6).values.tolist() if not centers.empty else [],
        "clusters": {
            "labels": [str(value) for value in cluster_table["cluster"].tolist()],
            "values": cluster_table["count"].astype(int).tolist(),
        },
    }


@app.get("/")
@app.get("/mobike-dashboard")
def dashboard():
    return render_template("mobike_dashboard.html")


@app.get("/api/dashboard")
def dashboard_data():
    try:
        return jsonify(dashboard_payload())
    except (FileNotFoundError, ValueError, KeyError) as error:
        return jsonify({"error": str(error)}), 500


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
